name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Oder die Version, die du benötigst

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build  # Hier wird der Build-Prozess ausgeführt

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Der NPM Token aus den Secrets
        run: |
          npm publish --access public
